import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pilih berat font yang kamu mau
  variable: "--font-poppins", // optional, untuk CSS variable
});

export const metadata = {
  title: "GetBaliTrip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-white" lang="en">
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
